#! /bin/sh

sxhkd -m -1 &

bspc config border_width 4
bspc config window_gap 0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config focus_follows_pointer true

bspc config normal_border_color "#103047"
bspc config active_border_color "#0493F9"
bspc config focused_border_color "#0493F9"

bspc monitor DP-4 -d 1 2 3 4 5
bspc monitor DP-2 -d 6 7 8 9 0

wmname LG3D &

/home/ben/.config/polybar/launch.sh
