#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias make="make -j9"

alias off="sudo shutdown -h now"
alias restart="sudo reboot"

function e {
    SOCKET_FILE=$(lsof -c emacs | grep server | tr -s " " | cut -d' ' -f9 | head -1)
    if [[ -n $(pgrep emacsclient) ]]; then
        nohup emacsclient -a '' -s $SOCKET_FILE $@ &>/dev/null &
    else
        nohup emacsclient -c -a '' -F "((fullscreen . maximized))" -s $SOCKET_FILE $@ &> /dev/null &
    fi
    disown
}

alias en="emacsclient"

export EDITOR="emacsclient"

# alias ls="ls -h "

alias clear="clear && ls"

function chpwd() {
    emulate -L zsh
    clear
    if [ -n "$INSIDE_EMACS" ]; then
        print -P "\033AnSiTc %d"
    fi
}

if [ -n "$INSIDE_EMACS" ]; then
    print -P "\033AnSiTu %n"
    print -P "\033AnSiTc %d"
fi

clear
